[package]
name = "kn-editor-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["rope"]
rope = []

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_wasm_bindgen = "0.6"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
# Optional high-performance rope; can be toggled off when not available
ropey = { version = "1", optional = true }

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true

