apiVersion: v1
kind: Namespace
metadata:
  name: knowledge-network
  labels:
    app.kubernetes.io/name: knowledge-network
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: namespace
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: knowledge-network-quota
  namespace: knowledge-network
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "20"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: knowledge-network-limits
  namespace: knowledge-network
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container
  - max:
      storage: 100Gi
    type: PersistentVolumeClaim